import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "surface-container": "#f2efd9",
        "tertiary-container": "#d4ffff",
        "on-tertiary-container": "#507878",
        "on-secondary-fixed-variant": "#474747",
        "inverse-on-surface": "#f5f1dc",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-fixed": "#e2e2e2",
        "surface-variant": "#e6e3ce",
        "surface": "#fdfae4",
        "surface-tint": "#626200",
        "on-secondary-container": "#646464",
        "on-surface": "#1c1c0f",
        "secondary": "#5e5e5e",
        "on-secondary-fixed": "#1b1b1b",
        "primary-container": "#ffff00",
        "on-error": "#ffffff",
        "on-primary-container": "#757500",
        "surface-container-high": "#ece9d3",
        "surface-container-highest": "#e6e3ce",
        "on-primary": "#ffffff",
        "surface-container-low": "#f7f4df",
        "surface-dim": "#dedbc6",
        "on-tertiary-fixed-variant": "#244d4e",
        "primary": "#626200",
        "tertiary-fixed": "#c0eaeb",
        "on-tertiary-fixed": "#002020",
        "background": "#fdfae4",
        "outline-variant": "#cac8aa",
        "on-surface-variant": "#484831",
        "primary-fixed": "#eaea00",
        "inverse-primary": "#cdcd00",
        "outline": "#79785f",
        "tertiary-fixed-dim": "#a4cece",
        "primary-fixed-dim": "#cdcd00",
        "secondary-fixed-dim": "#c6c6c6",
        "on-secondary": "#ffffff",
        "surface-bright": "#fdfae4",
        "tertiary": "#3d6565",
        "on-background": "#1c1c0f",
        "secondary-container": "#e2e2e2",
        "on-primary-fixed": "#1d1d00",
        "inverse-surface": "#323123",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#494900",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "48px",
        gutter: "24px",
        "margin-mobile": "16px",
        "grid-pattern-size": "32px",
        unit: "8px",
      },
      fontFamily: {
        "display-lg": ["var(--font-inter)", "sans-serif"],
        "mono-data": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "sans-serif"],
        "label-bold": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "mono-data": ["14px", { lineHeight: "1.5", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-bold": ["12px", { lineHeight: "1.4", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [
    forms,
    containerQueries,
  ],
};
export default config;